name: Input Test
description: 'Input Test'

inputs:
  secret:
    required: true
    type: string
    description: secret


runs:
  using: 'composite'
  steps:

    - name: Check Input
      shell: bash
      run: |
        
        echo "ALL INPUTS:"
        echo "secret=${{ inputs.secret }}"
        echo "secret2=${{ inputs.secret2 }}"
